spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coladder
    username: root
    password: 2354902964zjh
  data:
    redis:
      host: localhost
      port: 6379

model:
  api:
    url: "https://spark-api-open.xf-yun.com/v1/chat/completions"
    key: "ZrFMlFepmltxqdPWguJB:HOzZFhKHurQAyMAxClpI"



mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换update_time《=》updateTime

ok:
  http:
    connect-timeout: 360
    read-timeout: 60
    write-timeout: 360
    # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 200
    # 连接空闲时间最多为 300 秒
    keep-alive-duration: 300